print("Let's play Silly Sentences!")
name = input("Enter a name: ")
adjective1 = input("Enter a Adjective: ")
adjective2 = input("Enter a Adjective: ")
adverb = input("Enter a Adverb: ")
food = input("Enter a food: ")
food2 = input("Enter another food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ") 
print(" \n")
print( name + " was planning a dream vacation to " + place)
print( name + " was especially looking forward to trying the local cuisine, including " + adjective1 + food + " and " + food2 + "\n" )
print( name + " will have to practice the language " + adverb + "to make it easier to " + verb + " with people. \n")
print( name + " has a long list of sights to see, including the " + noun + " museum and the " + adjective2 + " park.")